#!/bin/bash

# Check or nix and install if we don't have it

if ! type "nix" &> /dev/null; then
  curl https://nixos.org/nix/install | sh
fi

# Source nix

. ~/.nix-profile/etc/profile.d/nix.sh

exit 0
