#!/bin/bash

# Check on nix and install if we don't have it

if ! type "nix" &> /dev/null; then
  if [[ $(uname -s) == 'Darwin' ]]; then
    sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
  else
    curl -L https://nixos.org/nix/install | sh
  fi
fi

# Source nix

. ~/.nix-profile/etc/profile.d/nix.sh

exit 0
