#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

declare -r NPM_AUTHOR_URL="https://robertwpearce.com"
declare -r NPM_EMAIL="me@robertwpearce.com"
declare -r NPM_LICENSE="BSD-3"
declare -r NPM_NAME="Robert Pearce"

function has_cmd {
  hash "${1}" 2> /dev/null
}

function main {
  if has_cmd npm; then
    npm config set init-author-name "${NPM_NAME}"
    npm config set init-author-email "${NPM_EMAIL}"
    npm config set init-author-url "${NPM_AUTHOR_URL}"
    npm config set init-license "${NPM_LICENSE}"
    npm config set init-version "0.1.0"
  fi
}

main
