#!/usr/bin/env bash

[[ ! -v DOTFILE_CFG ]] && echo "Error: DOTFILE_CFG is not set" && exit 1

nix build ".#darwinConfigurations.${DOTFILE_CFG}.system" --experimental-features "nix-command flakes"
./result/sw/bin/darwin-rebuild switch --flake ".#${DOTFILE_CFG}"
