#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

function main {
  ./bin/tool install xdg
  ./bin/tool install zsh
  ./bin/tool install conf
  ./bin/tool install ssh
  ./bin/tool install homebrew-work
  ./bin/tool install utils
}

main
