#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

## ==============================================================================

function main {
  # TODO
  return 0
}

main
