#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

function main {
  source "${CURRENT_DIR}"/tools/xdg/.vars

  "${CURRENT_DIR}"/bin/tool install xdg
  "${CURRENT_DIR}"/bin/tool install zsh
  "${CURRENT_DIR}"/bin/tool install macos-home
  "${CURRENT_DIR}"/bin/tool install conf
  "${CURRENT_DIR}"/bin/tool install ssh
  "${CURRENT_DIR}"/bin/tool install homebrew-home
  "${CURRENT_DIR}"/bin/tool install nix
  "${CURRENT_DIR}"/bin/tool install go
  "${CURRENT_DIR}"/bin/tool install haskell
  "${CURRENT_DIR}"/bin/tool install rust
  "${CURRENT_DIR}"/bin/tool install utils
}

main
