#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

function main {
  "${CURRENT_DIR}"/bin/tool install xdg
  "${CURRENT_DIR}"/bin/tool install zsh
  "${CURRENT_DIR}"/bin/tool install conf
  "${CURRENT_DIR}"/bin/tool install ssh
  "${CURRENT_DIR}"/bin/tool install homebrew-work
  "${CURRENT_DIR}"/bin/tool install utils
}

main
