#!/usr/bin/env bash

XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_HOME

set -e -o pipefail -p

# Keep the computer awake for the duration of this script.
[[ $(command -v caffeinate) ]] && caffeinate -dusw $$ &

# Ask for the administrator password
sudo -v

# sudo keep-alive
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# INT/TERM trap
trap 'exit 1' INT TERM

# Bunch of symlinks

ln -sfv "$XDG_CONFIG_HOME/runcom/.ackrc" ~
ln -sfv "$XDG_CONFIG_HOME/runcom/.bash_profile" ~
ln -sfv "$XDG_CONFIG_HOME/runcom/.gemrc" ~
ln -sfv "$XDG_CONFIG_HOME/runcom/.inputrc" ~
ln -sfv "$XDG_CONFIG_HOME/runcom/.nvimrc" ~
ln -sfv "$XDG_CONFIG_HOME/git/.gitconfig" ~

# macOS Install

if [[ $(uname -s) == 'Darwin' ]]; then
  if [[ -z "$(xcode-select -p)" ]]; then
    echo "Either XCode isn't installed or isn't linked. Install it, or link with xcode-select."
    exit 1
  fi

  . "$XDG_CONFIG_HOME/installs/homebrew"
  . "$XDG_CONFIG_HOME/installs/node"
  . "$XDG_CONFIG_HOME/installs/ruby"
  . "$XDG_CONFIG_HOME/installs/haskell"
  . "$XDG_CONFIG_HOME/installs/git"
  . "$XDG_CONFIG_HOME/installs/macos"
fi
