#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

export IS_WORK=true

function main {
  source "${CURRENT_DIR}"/tools/xdg/.vars

  "${CURRENT_DIR}"/bin/tool install xdg
  "${CURRENT_DIR}"/bin/tool install zsh
  "${CURRENT_DIR}"/bin/tool install macos-work
  "${CURRENT_DIR}"/bin/tool install conf
  "${CURRENT_DIR}"/bin/tool install ssh
  "${CURRENT_DIR}"/bin/tool install homebrew-work
  "${CURRENT_DIR}"/bin/tool install go
  "${CURRENT_DIR}"/bin/tool install utils
}

main
