#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

function has_cmd {
  hash "${1}" 2> /dev/null
}

function is_mac {
  [[ "$OSTYPE" =~ "darwin" ]] || return 1
}

function install_nix {
  if ! has_cmd nix; then
    echo "nix install: setting up nix..."

    if is_mac; then
      sh <(curl -L https://nixos.org/nix/install)
    else
      sh <(curl -L https://nixos.org/nix/install) --daemon
    fi

    # Set current user as trusted user
    echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon

    # shellcheck source=/dev/null
    source "${XDG_CONFIG_HOME}/zsh/.zshrc"

    nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  fi

  nix-channel --update
}

function install_cachix {
  if ! has_cmd cachix; then
    echo "nix install: setting up cachix..."
    nix-env -iA cachix -f https://cachix.org/api/v1/install
  fi
}

function install_devenv {
  if ! has_cmd devenv; then
    echo "nix install: setting up devenv..."
    nix-env -if https://github.com/cachix/devenv/tarball/latest
  fi
}

function main {
  install_nix
  install_cachix
  install_devenv
}

main
