#!/usr/bin/env bash

set -eou pipefail

function has_cmd {
  hash "${1}" 2> /dev/null
}

function main {
  if has_cmd go; then
    # Go language server (used by editors)
    go install golang.org/x/tools/gopls@latest

    # Linter aggregator
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    # Static analysis tool
    go install honnef.co/go/tools/cmd/staticcheck@latest

    # Go binary release tool
    go install github.com/goreleaser/goreleaser@latest

    # HTTP playground tool
    go install github.com/rpearce/httpwut@latest

    # Lightweight static site generator
    go install github.com/rpearce/ature@latest

    # CLI generator for Cobra
    go install github.com/spf13/cobra-cli@latest
  fi
}

main
