#!/usr/bin/env bash

set -Eeuo pipefail

function main {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  echo "homebrew uninstall: consider removing homebrew-related configs in ZSH configs"
}

main
