#!/usr/bin/env bash

APPLICATIONS_PATH="$HOME/Applications"
DOWNLOAD_PATH="$HOME/Downloads/Docker.dmg"
DOWNLOAD_URL="https://download.docker.com/mac/stable/Docker.dmg"
VOLUME_PATH="/Volumes/Docker"
VOLUME_APP_PATH="$VOLUME_PATH/Docker.app"

# download Docker

curl $DOWNLOAD_URL -o $DOWNLOAD_PATH

# mount the .dmg

hdiutil mount $DOWNLOAD_PATH

# copy the app to the Applications folder

cp -R $VOLUME_APP_PATH $APPLICATIONS_PATH

# unmount and detach

hdiutil detach $VOLUME_PATH

# remove the .dmg

rm $DOWNLOAD_PATH
