#!/usr/bin/env bash

# Check for Homebrew and install if we don't have it

if ! type "brew" &> /dev/null; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install from Brewfile

brew bundle -v --file="$XDG_CONFIG_HOME/installs/$1/Brewfile"

# Cleanup

brew update
brew upgrade
brew cleanup
brew doctor
brew cask upgrade

exit 0
