#!/usr/bin/env bash

# Check or nix and install if we don't have it

if test ! $(which nix); then
  curl https://nixos.org/nix/install | sh
fi

# Source nix

. ~/.nix-profile/etc/profile.d/nix.sh

# home-manager

if [[ $(uname -s) == 'Darwin' ]]; then
  mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
fi

if test ! $(which home-manager); then
  nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi
