#!/usr/bin/env bash

# Install NVM

curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | PROFILE=false bash

# Install latest node version

nvm install node
nvm alias default node

# Install yarn

curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
