#!/usr/bin/env bash

# Check for Homebrew and install if we don't have it

if ! type "brew" &> /dev/null; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

exit 0
