#!/bin/bash

# Check on nix and install if we don't have it

if ! type "nix" &> /dev/null; then
  if [[ $(uname -s) == 'Darwin' ]]; then
    sh <(curl -L https://nixos.org/nix/install)
  else
    sh <(curl -L https://nixos.org/nix/install) --daemon
  fi
fi

exit 0
