#!/usr/bin/env bash

set -Eeuo pipefail

CURRENT_DIR="$(dirname "$(realpath "$0")")"

function main {
  mkdir -p "${XDG_CONFIG_HOME}/utils"

  # repo-sync tool
  if ! command -v repo-sync >/dev/null; then
    curl -fL --proto '=https' --tlsv1.2 https://github.com/rpearce/repo-sync/releases/latest/download/repo-sync-macos-aarch64.tar.gz \
      | tar -xzf - -C "${XDG_CONFIG_HOME}/utils/"
  fi

  # retry tool
  ln -sf "${CURRENT_DIR}/retry" "${XDG_CONFIG_HOME}/utils/retry"
}

main
