#!/usr/bin/env bash

set -Eeuo pipefail

function has_cmd {
  hash "${1}" 2> /dev/null
}

function main {
  if ! has_cmd ghcup; then
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  fi
}

main
