#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

function has_cmd {
  hash "${1}" 2> /dev/null
}

function main {
  if has_cmd ghcup; then
    ghcup nuke
    echo "haskell uninstall: consider removing icu4c and llvm@13 from Brewfile, ghcup script from .zshrc"
  fi
}

main
