#!/usr/bin/env bash

set -Eeuo pipefail

function main {
  mkdir -p \
    "${XDG_CACHE_HOME}" \
    "${XDG_CONFIG_HOME}" \
    "${XDG_DATA_HOME}" \
    "${XDG_LIB_HOME}" \
    "${XDG_STATE_HOME}"
}

main
