#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

function main {
  rm -rf "${XDG_CACHE_HOME}"
  rm -rf "${XDG_CONFIG_HOME}"
  rm -rf "${XDG_DATA_HOME}"
  rm -rf "${XDG_LIB_HOME}"
  rm -rf "${XDG_STATE_HOME}"
}

main
