#!/usr/bin/env bash

set -Eeuo pipefail

function has_cmd {
  hash "${1}" 2> /dev/null
}

function main {
  if has_cmd rustup; then
    rustup update
  else
    # https://www.rust-lang.org/tools/install
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  fi
}

main
